baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Sanjay Janardhan'
theme = "paper"
[params]
    color = 'wheat'

    github = 'sanjj1'
    instagram = 'sanjj_1'

    name = 'Sanjay Janardhan'
    bio = 'this is my bio'

    monoDarkIcon = true